-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}

select
    'plb:::m:ga4_page_path_report::r:' || sha1(
        ifnull("DATE"::string, '')
        || ifnull("PROPERTY"::string, '')
        || ifnull("_FIVETRAN_ID"::string, '')
    ) as _plb_uuid,
    _fivetran_synced::timestamp as _plb_loaded_at
    {% for col in adapter.get_columns_in_relation(
        adapter.get_relation(
            database="FIVETRAN_DATABASE",
            schema="AF_GOOGLE_ANALYTICS",
            identifier="PAGE_PATH",
        )
    ) -%}, trim("{{col.column}}"::string) as "{{col.column}}" {% endfor %}
from "FIVETRAN_DATABASE"."AF_GOOGLE_ANALYTICS"."PAGE_PATH"
where 1 = 1
-- Make sure there is only one record per _plb_uuid, using the user-supplied composite
-- key.
qualify row_number() over (partition by _plb_uuid order by _plb_loaded_at desc) = 1

