-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}

select
    'plb:::m:gsc_keyword_page_report::r:' || sha1(
        ifnull("DATE"::string, '')
        || ifnull("SEARCH_TYPE"::string, '')
        || ifnull("SITE"::string, '')
        || ifnull("COUNTRY"::string, '')
        || ifnull("DEVICE"::string, '')
        || ifnull("PAGE"::string, '')
        || ifnull("QUERY"::string, '')
    ) as _plb_uuid,
    _fivetran_synced::timestamp as _plb_loaded_at
    {% for col in adapter.get_columns_in_relation(
        adapter.get_relation(
            database="FIVETRAN_DATABASE",
            schema="AF_PLIABLE_SOURCE_DB",
            identifier="KEYWORD_PAGE_REPORT",
        )
    ) -%}, trim("{{col.column}}"::string) as "{{col.column}}" {% endfor %}
from "FIVETRAN_DATABASE"."AF_PLIABLE_SOURCE_DB"."KEYWORD_PAGE_REPORT"
where 1 = 1
-- Make sure there is only one record per _plb_uuid, using the user-supplied composite
-- key.
qualify row_number() over (partition by _plb_uuid order by _plb_loaded_at desc) = 1

