-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}


with
    stacked as (

        (
            select
                _plb_uuid,
                _plb_loaded_at,
                'gsc_keyword_page_report' as _plb_source_model,
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."DATE"::string, '')
                    )
                ) as "DATE",
                (
                    concat_ws(
                        'None',
                        ifnull("gsc_keyword_page_report"."SEARCH_TYPE"::string, '')
                    )
                ) as "SEARCH_TYPE",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."SITE"::string, '')
                    )
                ) as "SITE",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."COUNTRY"::string, '')
                    )
                ) as "COUNTRY",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."DEVICE"::string, '')
                    )
                ) as "DEVICE",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."PAGE"::string, '')
                    )
                ) as "PAGE",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."QUERY"::string, '')
                    )
                ) as "QUERY",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."CLICKS"::string, '')
                    )
                ) as "CLICKS",
                (
                    concat_ws(
                        'None',
                        ifnull("gsc_keyword_page_report"."IMPRESSIONS"::string, '')
                    )
                ) as "IMPRESSIONS",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."CTR"::string, '')
                    )
                ) as "CTR",
                (
                    concat_ws(
                        'None', ifnull("gsc_keyword_page_report"."POSITION"::string, '')
                    )
                ) as "POSITION",
                null as "Extract Page"
            from {{ ref("gsc_keyword_page_report") }} as "gsc_keyword_page_report"

        )

    ),
    transformed as (

        select
            -- Generate a new deterministic UUID unique to this particular model
            'plb:::m:gsc_keyword_page_clean::r:' || sha1(_plb_uuid) as _plb_uuid,
            _plb_loaded_at as _plb_loaded_at,
            try_cast(("CLICKS")::string as varchar) as "CLICKS",
            try_cast(("COUNTRY")::string as varchar) as "COUNTRY",
            try_cast(("CTR")::string as varchar) as "CTR",
            try_cast(("DATE")::string as varchar) as "DATE",
            try_cast(("DEVICE")::string as varchar) as "DEVICE",
            try_cast((parse_url("PAGE"):path)::string as varchar) as "Extract Page",
            try_cast(("IMPRESSIONS")::string as varchar) as "IMPRESSIONS",
            try_cast(("PAGE")::string as varchar) as "PAGE",
            try_cast(("POSITION")::string as varchar) as "POSITION",
            try_cast(("QUERY")::string as varchar) as "QUERY",
            try_cast(("SEARCH_TYPE")::string as varchar) as "SEARCH_TYPE",
            try_cast(("SITE")::string as varchar) as "SITE"
        from stacked

    )

select *
from transformed
where 1 = 1

