-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}


with
    stacked as (

        (
            select
                _plb_uuid,
                _plb_loaded_at,
                'gsc_queries' as _plb_source_model,
                (
                    (
                        case
                            when
                                "gsc_queries"."QUERY"::string is null
                                or "gsc_queries"."QUERY"::string::string = ''
                            then null
                            else "gsc_queries"."QUERY"::string
                        end
                    )
                ) as "QUERY",
                null as "Brand Search"
            from {{ ref("gsc_queries") }} as "gsc_queries"

        )

    ),
    transformed as (

        select
            -- Generate a new deterministic UUID unique to this particular model
            'plb:::m:query::r:' || sha1(_plb_uuid) as _plb_uuid,
            _plb_loaded_at as _plb_loaded_at,
            try_cast(
                (
                    case when lower("QUERY") like '%andro%' then true else false end
                )::string as varchar
            ) as "Brand Search",
            try_cast(("QUERY")::string as varchar) as "QUERY"
        from stacked

    )

select *
from transformed
where 1 = 1

