-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}


with
    "e039865b1ca465468c55ca3263fae908" as (

        select
            "e039865b1ca465468c55ca3263fae908"."Page" as "Page",
            "e039865b1ca465468c55ca3263fae908"."QUERY" as "QUERY",
            any_value("e039865b1ca465468c55ca3263fae908"."COUNTRY") as "COUNTRY",
            any_value(
                "e039865b1ca465468c55ca3263fae908"."SEARCH_TYPE"
            ) as "SEARCH_TYPE",
            any_value("e039865b1ca465468c55ca3263fae908"."DEVICE") as "DEVICE",
            any_value("e039865b1ca465468c55ca3263fae908"."CLICKS") as "CLICKS",
            any_value("e039865b1ca465468c55ca3263fae908"."IMPRESSIONS") as "IMPRESSIONS"
        from {{ ref("organic_search_activity") }} as "e039865b1ca465468c55ca3263fae908"

        group by
            "e039865b1ca465468c55ca3263fae908"."Page",
            "e039865b1ca465468c55ca3263fae908"."QUERY"

    ),
    "c17380cdd423b1427d74f58b87feb1f4" as (

        select
            "e039865b1ca465468c55ca3263fae908"."Page" as "Page",
            "e039865b1ca465468c55ca3263fae908"."QUERY" as "QUERY",
            any_value(
                "c17380cdd423b1427d74f58b87feb1f4"."Brand Search"
            ) as "Brand Search"
        from {{ ref("organic_search_activity") }} as "e039865b1ca465468c55ca3263fae908"

        left join
            {{ ref("query") }} "c17380cdd423b1427d74f58b87feb1f4"
            on "c17380cdd423b1427d74f58b87feb1f4"._plb_uuid
            = "e039865b1ca465468c55ca3263fae908"."query_id"

        group by
            "e039865b1ca465468c55ca3263fae908"."Page",
            "e039865b1ca465468c55ca3263fae908"."QUERY"

    ),
    unioned_components as (
        select
            current_timestamp() as _plb_loaded_at,
            concat_ws(
                '|',
                "e039865b1ca465468c55ca3263fae908"."Page",
                "e039865b1ca465468c55ca3263fae908"."QUERY"
            ) as _plb_uuid,
            "e039865b1ca465468c55ca3263fae908"."Page",
            "e039865b1ca465468c55ca3263fae908"."QUERY",
            "e039865b1ca465468c55ca3263fae908"."COUNTRY",
            "e039865b1ca465468c55ca3263fae908"."SEARCH_TYPE",
            "e039865b1ca465468c55ca3263fae908"."DEVICE",
            "e039865b1ca465468c55ca3263fae908"."CLICKS",
            "e039865b1ca465468c55ca3263fae908"."IMPRESSIONS",
            "c17380cdd423b1427d74f58b87feb1f4"."Brand Search"
        from "e039865b1ca465468c55ca3263fae908"
        left join
            "c17380cdd423b1427d74f58b87feb1f4"
            on (
                "e039865b1ca465468c55ca3263fae908"."Page"
                = "c17380cdd423b1427d74f58b87feb1f4"."Page"
                and "e039865b1ca465468c55ca3263fae908"."QUERY"
                = "c17380cdd423b1427d74f58b87feb1f4"."QUERY"
            )
    ),
    transformed as (

        select
            -- Generate a new deterministic UUID unique to this particular model
            'plb:::m:organic_search_events::r:' || sha1(_plb_uuid) as _plb_uuid,
            _plb_loaded_at as _plb_loaded_at,
            try_cast(("Page")::string as varchar) as "Page",
            try_cast(("QUERY")::string as varchar) as "QUERY",
            try_cast(("Brand Search")::string as varchar) as "Brand Search",
            try_cast(("CLICKS")::string as varchar) as "CLICKS",
            try_cast(("COUNTRY")::string as varchar) as "COUNTRY",
            try_cast(("DEVICE")::string as varchar) as "DEVICE",
            try_cast(("IMPRESSIONS")::string as varchar) as "IMPRESSIONS",
            try_cast(("SEARCH_TYPE")::string as varchar) as "SEARCH_TYPE"
        from unioned_components

    )

select *
from transformed
where 1 = 1

