-- This file was automatically generated by PLIABLE (https://app.pliable.co). 
-- Please do not edit this file directly, as it will be overwritten the next time someone commits their changes in Pliable.

{{ config(materialized="table") }}


with
    group_assignments as (
        select
            _plb_uuid,
            'plb:::m:gsc_queries::r:' || sha1(_plb_merge_key) as _plb_group_id
        from
            (

                (
                    select
                        _plb_uuid,
                        concat_ws(
                            '|',
                            ifnull(
                                (
                                    (
                                        case
                                            when
                                                "gsc_keyword_page_report"."QUERY"
                                                ::string
                                                is null
                                                or "gsc_keyword_page_report"."QUERY"
                                                ::string::string
                                                = ''
                                            then null
                                            else
                                                "gsc_keyword_page_report"."QUERY"
                                                ::string
                                        end
                                    )
                                ),
                                _plb_uuid
                            )
                        ) as _plb_merge_key
                    from
                        {{ ref("gsc_keyword_page_report") }}
                        as "gsc_keyword_page_report"
                )

            )
    ),
    final_group_assignments as (select * from group_assignments),
    "gsc_keyword_page_report" as (
        select s.*, g._plb_group_id
        from {{ ref("gsc_keyword_page_report") }} s
        left join final_group_assignments g on g._plb_uuid = s._plb_uuid
    ),
    summarized as (
        select
            _plb_group_id as _plb_uuid,
            max(_plb_loaded_at) as _plb_loaded_at,
            any_value(
                (
                    (
                        case
                            when
                                "gsc_keyword_page_report"."QUERY"::string is null
                                or "gsc_keyword_page_report"."QUERY"::string::string
                                = ''
                            then null
                            else "gsc_keyword_page_report"."QUERY"::string
                        end
                    )
                )
            ) as "QUERY"
        from "gsc_keyword_page_report"
        group by _plb_group_id
    ),
    transformed as (

        select
            -- Generate a new deterministic UUID unique to this particular model
            'plb:::m:gsc_queries::r:' || sha1(_plb_uuid) as _plb_uuid,
            _plb_loaded_at as _plb_loaded_at,
            try_cast(("QUERY")::string as varchar) as "QUERY"
        from summarized

    )

select *
from transformed
where 1 = 1

